name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run eslint

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Deploy to Render
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  notify:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Success
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: "✅ Deployment succeeded for commit ${{ github.sha }} by ${{ github.actor }}."
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: |
            ❌ Deployment failed!
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Message: ${{ github.event.head_commit.message }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
